services: 
  backend:
    image: nestJS-task-app/backend:latest
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
      mailhog: 
        condition: service_started
    restart: unless-stopped
    tty: true
    ports:
      - 8000:8000
    env_file:
      - ./.env
    environment:  
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=nestJSTest
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwerty123  
      - DATABASE_URL=postgresql://postgres:qwerty123@postgres:5432/nestJSTest?schema=public
      - MAIL_HOST=mailhog  

    volumes:
      - .:/app
      - backend-node-modules:/app/node_modules 
      # - backend-dist:/app/dist   
    networks:
      - app-network

  postgres:
    image: postgres
    container_name: postgres 
    restart: unless-stopped  
    environment:
      - POSTGRES_DB=nestJSTest
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwerty123 
    ports:
      - 5432:5432
    volumes:
      - postgres-db:/var/lib/postgresql/data  
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d nestJSTest"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network


  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    restart: unless-stopped
    ports:
      - 8025:8025
      - 1025:1025
    networks:
      - app-network

volumes:
  postgres-db: 
  backend-node-modules:
  # backend-dist:
    

networks:
  app-network:
    driver: bridge