services: 
  postgres:
    image: postgres
    container_name: postgres 
    restart: unless-stopped  
    environment:
      - POSTGRES_DB=nestJSTest
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwerty123 
    ports:
      - 5432:5432
    volumes:
      - postgres-db:/var/lib/postgresql/data  


volumes:
  postgres-db: 